### ISSUE TITLE
integration with condo?

### ISSUE THREAD

**Issue by datatalking** [mikeckennedy/cookiecutter-pyramid-talk-python-starter#3]
Hi Michael, when I run this program from the CLI it works flawlessly.

Thank you for a well-documented tutorial.

Then when I drag the icon into pycharm it doesn't seem to be set up for working with Conda which I prefer to use for managing my dependencies.

The errors I'm getting are below.

`/Users/owner/miniconda3/envs/my_web_app/bin/python "/Users/owner/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-1/182.3341.8/PyCharm 2018.2 EAP.app/Contents/helpers/pycharm/pycharm_load_entry_point.py" /Users/owner/Desktop/project_area/my_web_app/development.ini
Traceback (most recent call last):
  File "/Users/owner/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-1/182.3341.8/PyCharm 2018.2 EAP.app/Contents/helpers/pycharm/pycharm_load_entry_point.py", line 12, in <module>
    sys.exit(f())
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/pyramid/scripts/pserve.py", line 227, in run
    server = server_loader.get_wsgi_server(server_name, config_vars)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/plaster_pastedeploy/__init__.py", line 152, in get_wsgi_server
    global_conf=defaults)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 255, in loadserver
    return loadobj(SERVER, uri, name=name, **kw)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/owner/miniconda3/envs/my_web_app/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'waitress' distribution was not found and is required by the application`

**Comment by mikeckennedy** [comment]
Hi, did you `pip3 install -r requirements-dev.txt`? It seems waitress is missing and the setup.py only installs the prod settings but not the dev ones. Maybe you can conda install -r ... ;)

**Comment by datatalking** [comment]
I was able to get it working. Thank!

**Comment by mikeckennedy** [comment]
Great to hear. :)
